name: SSL Expiry Check

on:
  schedule:
    - cron: '0 9 * * *'  # Schedule the workflow to run daily

jobs:
  check-ssl-expiry:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y openssl

      - name: Read domain list from file
        run: |
          cat domains.txt | while read domain; do
            expiry_date=$(echo | openssl s_client -servername $domain -connect $domain:443 2>/dev/null | openssl x509 -noout -dates | grep "notAfter" | cut -d "=" -f 2)
            current_date=$(date +%s)
            expiry_epoch=$(date -d "$expiry_date" +%s)
            days_to_expire=$(( ($expiry_epoch - $current_date) / (60 * 60 * 24) ))
            
            if [ $days_to_expire -lt 30 ]; then
              echo "SSL Expiry Alert\n   * Domain: $domain\n   * Warning: The SSL certificate for $domain will expire in $days_to_expire days." > alert.txt
              cat alert.txt | curl -X POST -H "Content-type: application/json" --data @- $SLACK_WEBHOOK_URL
            fi
          done
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
