name: SSL Expiry Check

#on:
  #push:
   # branches:
    #  - main
on:
  schedule:
   - cron: '0 22 * * *' # Run every day at midnight
 
jobs:
  ssl_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          echo "SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL }}" >> $GITHUB_ENV

      - name: Copy domains file
        run: cp domains.txt .github/alert/

      - name: Run SSL check script
        run: |
          bash .github/alert/myscript.ssh
