# This is a basic workflow to help you get started with Actions

name: SSL Expiry Check Alert

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 9 * * *'  # Schedule the workflow to run daily
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  #build:
    # The type of runner that the job will run on
        runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install required tools
        run: 
        sudo apt-get update
        sudo apt-get install -y openssl

      # Runs a set of commands using the runners shell
      - name: Read domain list from file in the root
        run: cat domains.txt | while read domain; do
            expiry_date=$(echo | openssl s_client -servername $domain -connect $domain:443 2>/dev/null | openssl x509 -noout -dates | grep "notAfter" | cut -d "=" -f 2)
            current_date=$(date +%s)
            expiry_epoch=$(date -d "$expiry_date" +%s)
            days_to_expire=$(( ($expiry_epoch - $current_date) / (60 * 60 * 24) ))
           
            if [ $days_to_expire -lt 30 ]; then
              echo "SSL Expiry Alert\n   * Domain: $domain\n   * Warning: The SSL certificate for $domain will expire in $days_to_expire days." > alert.txt
              cat alert.txt | curl -X POST -H "Content-type: application/json" --data @- $SLACK_WEBHOOK_URL
            fi
          done
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          
          echo Add other actions to build,
          echo test, and deploy your project.
